// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

#nullable disable

namespace april2020.Migrations
{
    [DbContext(typeof(VideoKlubContext))]
    [Migration("20220324013607_V7")]
    partial class V7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Models.Polica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("MaxBrDVDs")
                        .HasColumnType("int");

                    b.Property<string>("Oznaka")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("TrenutnoDVDs")
                        .HasColumnType("int");

                    b.Property<int?>("mojiVKID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("mojiVKID");

                    b.ToTable("Police");
                });

            modelBuilder.Entity("Models.VideoKlub", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.HasKey("ID");

                    b.ToTable("VideoKlubovi");
                });

            modelBuilder.Entity("Models.Polica", b =>
                {
                    b.HasOne("Models.VideoKlub", "mojiVK")
                        .WithMany("mojePolice")
                        .HasForeignKey("mojiVKID");

                    b.Navigation("mojiVK");
                });

            modelBuilder.Entity("Models.VideoKlub", b =>
                {
                    b.Navigation("mojePolice");
                });
#pragma warning restore 612, 618
        }
    }
}
